- hosts: grafana
  tasks:
    - name: Import Grafana dashboard
      grafana_dashboard:
        grafana_url: "{{ grafana_url }}"
        grafana_api_key: "{{ grafana_api_key }}"
        state: present
        message: Updated by ansible
        overwrite: yes
        path: /root/dash.json
    
    - name: Create influxdb datasource
      grafana_datasource:
        name: "datasource-influxdb"
        grafana_url: "{{ grafana_url }}"
        grafana_api_key: "{{ grafana_api_key }}"
        org_id: "1"
        ds_type: "influxdb"
        ds_url: "{{ datasource_url }}"
        database: "{{ influx_db_name }}"
        time_interval: ">10s"
        password: "{{ influx_db_pass }}"

  become: true

    