{
 "title": "Pvesw-Vosk",
 "description": "InfluxDB dashboards for telegraf metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server/"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /$server/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server/"
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(\"usage_iowait\"), 1s) FROM \"cpu\" WHERE \"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent", "label": "%" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "SELECT mean(load1) as short,mean(load5) as medium,mean(load15) as long FROM \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s)*8 as \"in\"  FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(bytes_sent),1s)*8 as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(packets_recv), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(packets_sent), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk usage for $mountpoint",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" =~ /^$mountpoint$/AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per-cpu usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage for $cpu",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "repeat": "cpu",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $cpu $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "cpu_percentageBusy",
       "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network stack (TCP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TCP connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT mean(tcp_close) as CLOSED, mean(tcp_close_wait) as CLOSE_WAIT, mean(tcp_closing) as CLOSING, mean(tcp_established) as ESTABLISHED, mean(tcp_fin_wait1) as FIN_WAIT1, mean(tcp_fin_wait2) as FIN_WAIT2, mean(tcp_last_ack) as LAST_ACK, mean(tcp_syn_recv) as SYN_RECV, mean(tcp_syn_sent) as SYN_SENT, mean(tcp_time_wait) as TIME_WAIT FROM \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TCP aborts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "on close",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnClose" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "on data",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnData" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "timeout",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnTimeout" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "failed",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortFailed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "linger",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnLinger" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "memory",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnMemory" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP handshake issues",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "estabresets",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "outrsts",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(tcp_outrsts), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "activeopens",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(tcp_activeopens), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "passiveopens",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(tcp_passiveopens), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP SYN cookies",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "failed",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtSyncookiesFailed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "received",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtSyncookiesRecv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "sent",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtSyncookiesSent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "ICMP packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "in echos",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpInEchos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out echos",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpOutEchos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in echo responses",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpInEchoReps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out echo responses",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpOutEchoReps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "ICMP errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "in errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpInErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpOutErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "checksum errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpInCsumErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "IPv4 errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "in discards",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpInDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out discards",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpOutDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in hdr errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpInHdrErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in addr errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpInAddrErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out no routes",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpOutNoRoutes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in unknown protocol",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpInUnknownProtos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "IPv6 errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "in discards",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6InDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out discards",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6OutDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in hdr errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6InHdrErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in addr errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6InAddrErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out no routes",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6OutNoRoutes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in unknown protocol",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6InUnknownProtos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Swap I/O bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "swap_in",
       "query": "SELECT non_negative_derivative(mean(\"in\")) as \"in\", non_negative_derivative(mean(\"out\")) as \"out\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Swap usage (bytes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "swap_in",
       "query": "SELECT mean(used) as \"used\", mean(total) as \"total\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IOPS for /dev/$disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "disk",
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk I/O requests for /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O bytes for /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O time for /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "repeat": "mountpoint",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk inodes for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_free) + mean(inodes_used) as \"total\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}